version: "2"
services:
    convertigo:
        image: "convertigo/convertigo-ci:release/7.8.0"
        ports:
         - "28080:28080"
        links:
         - couchdb
        volumes:
         - workspace:/workspace
        environment:
         - JAVA_OPTS=
           -Dconvertigo.engine.fullsync.couch.username=admin
           -Dconvertigo.engine.fullsync.couch.password=fullsyncpassword
    couchdb:
        image: "couchdb:2.3.1"
        ports:
         - "28081:5984"
        environment:
         - COUCHDB_USER=admin
         - COUCHDB_PASSWORD=fullsyncpassword
        volumes:
         - couchdb:/opt/couchdb/data
volumes:
    workspace:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $PWD/workspace
    couchdb:  
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $PWD/couchdb



