version: "2"
services:
    convertigo:
        image: "convertigo:7.9.0"
        cap_add:
         - SYS_ADMIN
        command: bash -c "echo 'kernel.unprivileged_userns_clone=1' > /etc/sysctl.d/userns.conf ; /docker-entrypoint.sh convertigo"
        ports:
         - "28080:28080"
         - "443:8443"
        links:
         - couchdb
        volumes:
         - workspace:/workspace
         - tomcat_conf:/usr/local/tomcat/conf
         - tomcat_logs:/usr/local/tomcat/logs
        environment:
         - JAVA_OPTS=
           -Dconvertigo.engine.fullsync.couch.username=admin
           -Dconvertigo.engine.fullsync.couch.password=fullsyncpassword
           --add-exports=java.desktop/sun.java2d=ALL-UNNAMED
           --add-exports=java.base/sun.nio.cs
    couchdb:
        image: "couchdb:2.3.1"
        ports:
         - "28081:5984"
        environment:
         - COUCHDB_USER=admin
         - COUCHDB_PASSWORD=fullsyncpassword
        volumes:
         - couchdb:/opt/couchdb/data
volumes:
    workspace:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $PWD/workspace
    couchdb:  
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $PWD/couchdb
    tomcat_conf:  
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $PWD/tomcat/conf
    tomcat_logs:  
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $PWD/tomcat/logs