version: 2
jobs:
  deployEnvTest:
    docker:
    - image: convertigo/builder-ci:circleci-4
    steps:
    - checkout
    - run: |
        sh gradlew --no-daemon --stacktrace --info car deploy -Pconvertigo.load.mobileApplicationEndpoint=${testEndpoint} -Pconvertigo.deploy.server=${testDeployServer} -Pconvertigo.deploy.user=${testUserAdmin} -Pconvertigo.deploy.password=${testUserPassword}
        cp /home/circleci/project/build/C8Oforms.car /home/circleci/project/c8oforms_standalone/workspace/projects/C8Oforms.car
        cd /home/circleci/project/ && tar -czvf c8oforms_standalone.tar.gz c8oforms_standalone
        aws s3 cp --acl public-read c8oforms_standalone.tar.gz s3://c8oforms/c8oforms_standalone_${CIRCLE_TAG}.tar.gz
        cd /home/circleci/project/build/ && aws s3 cp --acl public-read C8Oforms.car s3://c8oforms/C8Oforms_${CIRCLE_TAG}.car
    - store_artifacts:
        path: /home/circleci/project/build/C8Oforms.car
    - store_artifacts:
        path: /home/circleci/project/build/Convertigo\ Forms\ Builder_Android.apk
    - store_artifacts:
        path: /home/circleci/project/c8oforms_standalone.tar.gz

  deployEnvProd: 
    docker:
    - image: circleci/openjdk:11-jdk
    steps:
    - checkout
    - run: |
        sh gradlew --no-daemon --stacktrace --info car downloadNativeBuild deploy -Pconvertigo.load.mobileApplicationEndpoint=${ProdEndpoint} -Pconvertigo.deploy.server=${ProdDeployServer} -Pconvertigo.deploy.user=${ProdUserAdmin} -Pconvertigo.deploy.password=${ProdUserPassword}
        cp /home/circleci/project/build/C8Oforms.car /home/circleci/project/c8oforms_standalone/workspace/projects/C8Oforms.car
        cd /home/circleci/project/ && tar -czvf c8oforms_standalone.tar.gz c8oforms_standalone
        aws s3 cp --acl public-read c8oforms_standalone.tar.gz s3://c8oforms/c8oforms_standalone_${CIRCLE_TAG}.tar.gz
        cd /home/circleci/project/build/ && aws s3 cp --acl public-read C8Oforms.car s3://c8oforms/C8Oforms_${CIRCLE_TAG}.car
    - store_artifacts:
        path: /home/circleci/project/build/C8Oforms.car
    - store_artifacts:
        path: /home/circleci/project/build/Convertigo\ Forms\ Builder_Android.apk
    - store_artifacts:
        path: /home/circleci/project/c8oforms_standalone.tar.gz
workflows:
  version: 2
  buildOrDeploy:
    jobs:
      - deployEnvTest:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+-beta\d*$/
      - deployEnvProd:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/