version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:11-jdk
    steps:
    - checkout
    - run: |
        sh gradlew --no-daemon --stacktrace --info car downloadNativeBuild
        echo "ls -lh"
        ls -lh
        echo "ls -lh build"
        ls -lh build
        echo "ls -lh DisplayObjects/mobile/build"
        ls -lh DisplayObjects/mobile/build
workflows:
  version: 2
  all:
    jobs:
    - build