version: 2
jobs:
  buildDeployTestConvertigo:
    docker:
    - image: circleci/openjdk:11-jdk
    steps:
    - checkout
    - run: |
        sh gradlew --no-daemon --stacktrace --info car deploy -Pconvertigo.load.mobileApplicationEndpoint=https://test-convertigo.convertigo.net/convertigo -Pconvertigo.deploy.server=https://test-convertigo.convertigo.net/convertigo -Pconvertigo.deploy.user=admin -Pconvertigo.deploy.password=76ace4687f046ba4f066bd9a1d53fe6dd1b70697
        echo "ls -lh"
        ls -lh
        echo "ls -lh build"
        ls -lh build
        echo "ls -lh DisplayObjects/mobile/build"
        ls -lh DisplayObjects/mobile/build
workflows:
  version: 2
  buildDeployTestConvertigo:
    jobs:
    - buildDeployTestConvertigo
        filters:
          branches:
            only: develop