version: 2
jobs:
  deployEnvTest:
    docker:
    - image: circleci/openjdk:11-jdk
    steps:
    - checkout
    - run: |
        sh gradlew --no-daemon --stacktrace --info car deploy -Pconvertigo.load.mobileApplicationEndpoint=${testEndpoint} -Pconvertigo.deploy.server=${testDeployServer} -Pconvertigo.deploy.user=${testUserAdmin} -Pconvertigo.deploy.password=${testUserPassword}
        cp /home/circleci/project/build/C8Oforms.car /home/circleci/project/c8oforms_standalone/workspace/projects/C8Oforms.car
        cd /home/circleci/project/ && tar -czvf c8oforms_standalone.tar.gz c8oforms_standalone
    - store_artifacts:
                path: /home/circleci/project/build/C8Oforms.car
    - store_artifacts:
                path: /home/circleci/project/build/Convertigo\ Forms\ Builder_Android.apk
    - store_artifacts:
                path: /home/circleci/project/c8oforms_standalone.tar.gz

  deployEnvProd:
    docker:
    - image: circleci/openjdk:11-jdk
    steps:
    - checkout
    - run: |
        sh gradlew --no-daemon --stacktrace --info car downloadNativeBuild deploy -Pconvertigo.load.mobileApplicationEndpoint=${ProdEndpoint} -Pconvertigo.deploy.server=${ProdDeployServer} -Pconvertigo.deploy.user=${ProdUserAdmin} -Pconvertigo.deploy.password=${ProdUserPassword}
        echo "ls -lh"
        ls -lh
        echo "ls -lh build"
        ls -lh build
        echo "ls -lh DisplayObjects/mobile/build"
        ls -lh DisplayObjects/mobile/build
    - store_artifacts:
                path: /home/circleci/project/build/C8Oforms.car
    - store_artifacts:
                path: /home/circleci/project/build/Convertigo\ Forms\ Builder_Android.apk

  generateAndCompileProd:
    docker:
    - image: circleci/openjdk:11-jdk
    steps:
    - checkout
    - run: |
        sh gradlew --no-daemon --stacktrace --info car compileMobileBuilder
        echo "ls -lh"
        ls -lh
        echo "ls -lh build"
        ls -lh build
        echo "ls -lh DisplayObjects/mobile/build"
        ls -lh DisplayObjects/mobile/build
    - store_artifacts:
                path: /home/circleci/project/build/C8Oforms.car
workflows:
  version: 2
  buildOrDeploy:
    jobs:
      - deployEnvTest:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+-beta\d*$/
      - deployEnvProd:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - generateAndCompileProd