version: 2
jobs:
  generateBuildAndCar:
    docker:
    - image: circleci/openjdk:11-jdk
    steps:
    - checkout
    - run: |
        sh gradlew --no-daemon --stacktrace --info car
    - store_artifacts:
                path: /home/circleci/project/build/C8Oforms.car

  deployEnvTest:
    docker:
    - image: circleci/openjdk:11-jdk
    steps:
    - checkout
    - run: |
        sh gradlew --no-daemon --stacktrace --info deploy -Pconvertigo.load.mobileApplicationEndpoint=${testEndpoint} -Pconvertigo.deploy.server=${testDeployServer} -Pconvertigo.deploy.user=${testUserAdmin} -Pconvertigo.deploy.password=${testUserPassword}
        echo "ls -lh"
        ls -lh
        echo "ls -lh build"
        ls -lh build
        echo "ls -lh DisplayObjects/mobile/build"
        ls -lh DisplayObjects/mobile/build
    - store_artifacts:
                path: /home/circleci/project/build/C8Oforms.car

  buildDeployTestConvertigo:
    docker:
    - image: circleci/openjdk:11-jdk
    steps:
    - checkout
    - run: |
        sh gradlew --no-daemon --stacktrace --info car deploy -Pconvertigo.load.mobileApplicationEndpoint=https://test-convertigo.convertigo.net/convertigo -Pconvertigo.deploy.server=https://test-convertigo.convertigo.net/convertigo -Pconvertigo.deploy.user=admin -Pconvertigo.deploy.password=76ace4687f046ba4f066bd9a1d53fe6dd1b70697
        echo "ls -lh"
        ls -lh
        echo "ls -lh build"
        ls -lh build
        echo "ls -lh DisplayObjects/mobile/build"
        ls -lh DisplayObjects/mobile/build
    - store_artifacts:
                path: /home/circleci/project/build/C8Oforms.car

  buildDeployChantiers:
    docker:
    - image: circleci/openjdk:11-jdk
    steps:
    - checkout
    - run: |
        sh gradlew --no-daemon --stacktrace --info car deploy -Pconvertigo.load.mobileApplicationEndpoint=https://chantiers-atlantique.convertigo.net/convertigo -Pconvertigo.deploy.server=https://chantiers-atlantique.convertigo.net/convertigo -Pconvertigo.deploy.user=admin -Pconvertigo.deploy.password=acf048dff9a6dfcda30b74b0df694cf47d7ba1a3
        echo "ls -lh"
        ls -lh
        echo "ls -lh build"
        ls -lh build
        echo "ls -lh DisplayObjects/mobile/build"
        ls -lh DisplayObjects/mobile/build
    - store_artifacts:
                path: /home/circleci/project/build/C8Oforms.car

  generateAndCompileProd:
    docker:
    - image: circleci/openjdk:11-jdk
    steps:
    - checkout
    - run: |
        sh gradlew --no-daemon --stacktrace --info car compileMobileBuilder
        echo "ls -lh"
        ls -lh
        echo "ls -lh build"
        ls -lh build
        echo "ls -lh DisplayObjects/mobile/build"
        ls -lh DisplayObjects/mobile/build
    - store_artifacts:
                path: /home/circleci/project/build/C8Oforms.car
workflows:
  version: 2
  buildOrDeploy:
    jobs:
      - deployEnvTest:
          requires:
            - generateBuildAndCar
          filters:
            branches:
              only: develop
      - buildDeployChantiers:
          filters:
            branches:
              only: master
      - generateAndCompileProd:
          filters:
            branches:
              ignore:
                - master
                - develop