↓override_user_settings [steps.SimpleStep-1727792344732]: 
  expression: |
    '// Imports and helpers functions
    include("js/common.js");
    
    let loglevel = "warn";
    let authenticatedUserID = context.getAuthenticatedUser();
    try{
       meta = JSON.parse(meta);
    }
    catch(e){
       meta = {};
    }
    
    if(authenticatedUserID != null && authenticatedUserID != ""){
    	console.log("meta", meta, loglevel);
    	meta["_id"] = "C8Oreserved_"+authenticatedUserID;
    	delete meta["_rev"];
    	// post doc 
    	doc = toJSON(fsclient.postDocument(java.lang.String("c8oforms_fs"), toJettison(meta), new HashMap(), enums.CouchPostDocumentPolicy.merge, new HashMap(), false));
    	
    }
    '
↓meta [variables.RequestableVariable-1727792380030]: 