↓authenticatedUserID [steps.GetAuthenticatedUserStep-1694423675395]: 
↓authenticatedUserID1 [steps.SimpleSourceStep-1694423794430]: 
  sourceDefinition: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
      - com.twinsoft.convertigo.beans.common.XMLVector: 
        - java.lang.String: 
          - ↑value: 1694423675395
        - java.lang.String: 
          - ↑value: ./text()
  variableName: authenticatedUserID
↓getCurrentUserSettings [steps.SimpleStep-1694423739719]: 
  expression: |
    'var fsclient = com.twinsoft.convertigo.engine.Engine.theApp.couchDbManager.getFullSyncClient();
    var toJSON = function (json) {
       return JSON.parse(json.toString());
    }
    var toJettison = function (json) {
       var txt = (typeof json == "string") ? json : JSON.stringify(json);
       return txt.startsWith("{") ? new org.codehaus.jettison.json.JSONObject(txt) : new org.codehaus.jettison.json.JSONArray(txt);
    }
    let res = toJSON(fsclient.getDocument("c8oforms_fs", ''C8Oreserved_''+authenticatedUserID));
    '
↓object2 [steps.JsonToXmlStep-1694423843221]: 
  jsonObject: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.steps.SmartType
      - SmartType: 
        - ↑mode: JS
        - →→: res
  key: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.steps.SmartType
      - SmartType: 
        - ↑mode: PLAIN
        - →→: res