accessibility: Hidden
↓authenticatedUserID [steps.GetAuthenticatedUserStep-1694423675395]: 
↓authenticatedUserID1 [steps.SimpleSourceStep-1694423794430]: 
  sourceDefinition: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
      - com.twinsoft.convertigo.beans.common.XMLVector: 
        - java.lang.String: 
          - ↑value: 1694423675395
        - java.lang.String: 
          - ↑value: ./text()
  variableName: authenticatedUserID
↓getCurrentUserSettings [steps.SimpleStep-1694423739719]: 
  expression: |
    '// Imports and helpers functions
    include("js/common.js");
    let res = toJSON(fsclient.getDocument("c8oforms_fs", ''C8Oreserved_''+authenticatedUserID));
    
    // get current user rights
    var editing_rights = res.editing_rights == undefined ? editing_apps_default_rights == "true" : (res.editing_rights === true || res.editing_rights == "true");
    var nocode_db_rights = res.nocode_db_rights == undefined ? no_code_db_default_rights == "true" : (res.nocode_db_rights === true || res.nocode_db_rights == "true");
    var admin = res.admin != undefined && (res.admin === true || res.admin == "true");
    res.editing_rights = editing_rights;
    res.nocode_db_rights = nocode_db_rights;
    
    
    // if user has all rights no need to search forward in groups to find other rights
    if(editing_rights && nocode_db_rights && admin){
    	
    }
    else{
    	//search in groups rights
    	var groups = callSequence("lib_FullSyncGrp", "GroupsOf", { user: authenticatedUserID }).document.group;
    	if(groups != undefined){
    		if(!Array.isArray(groups)){
    			groups = [groups];
    		}
    		query = new HashMap();
    		query.put(''reduce'', ''false'');
    		query.put(''include_docs'', ''true'');
    		keys = toJettison(groups);
    		groups = toJSON(fsclient.postView("c8oforms_fs", ''groups'', ''rightsByUser'', query, keys)).rows;
    		console.log("my groups :", groups, "warn");
    		if(groups != undefined){
    			for(var group of groups){
    				if(!editing_rights){
    					editing_rights = group.doc.editing_rights;
    				}
    				if(!nocode_db_rights){
    					nocode_db_rights = group.doc.nocode_db_rights;
    				}
    				if(!admin){
    					admin = group.doc.admin;
    				}
    				if(editing_rights && nocode_db_rights && admin){
    					break;
    				}
    			}
    		}
    		res.editing_rights = editing_rights;
    		res.nocode_db_rights = nocode_db_rights;
    		res.admin = admin;
    	}
    }'
↓object2 [steps.JsonToXmlStep-1694423843221]: 
  jsonObject: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.steps.SmartType
      - SmartType: 
        - ↑mode: JS
        - →→: res
  key: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.steps.SmartType
      - SmartType: 
        - ↑mode: PLAIN
        - →→: res
↓no_code_db_default_rights [variables.RequestableVariable-1744201146791]: 
  value: ${C8Oforms.no_code_db_rights_default_enabled=true}
↓editing_apps_default_rights [variables.RequestableVariable-1744201146794]: 
  value: ${C8Oforms.editing_rights_default_enabled=true}