↓selectedForm [ngx.components.UIStackVariable-1789391281836]: 
↓pageOwner [ngx.components.UIStackVariable-1789391281838]: 
↓ModalPage [ngx.components.UIDynamicAction-1789391281840]: 
  beanData: |
    '{
     "ionBean": "ModalAction",
     "page": "plain:C8Oforms.MobileApplication.Application.applicationHistoryPage",
     "data": "script:{form: params.selectedForm, pageOwner: params.pageOwner}",
     "showBackdrop": "plain:false",
     "cssClass": "plain:modal-custom modal-custom--h-90"
    }'