C8Oforms.baserow.iframe=%BASEROW_PUBLIC_URL%/c8o/
lib_baserow.https=false
lib_baserow.port=8000
lib_baserow.server=baserow
lib_baserow.adminuser=admin@convertigo.com
lib_baserow.password.secret=x701301a25336f85870cef65c4c7b4b1b56fd1ac5c3496db716f30ea60a29ebea