↓item [ngx.components.UICompVariable-1776605300001]: 
  value: 
↓DivSettings [ngx.components.UIDynamicElement-1776605300002]: 
  beanData: '{"ionBean":"DivTag"}'
  tagName: div
  ↓AttrClass [ngx.components.UIAttribute-1776605300003]: 
    attrName: class
    attrValue: 
      - xmlizable: 
        - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
        - MobileSmartSourceType: plain:c8o-settings-stack
  ↓UseType [ngx.components.UIUseShared-1776605300004]: 
    sharedcomponent: C8Oforms.MobileApplication.Application.ToggleSwitch
    ↓label [ngx.components.UIUseVariable-1776605300005]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:this.translate.instant('chart_type')
    ↓options [ngx.components.UIUseVariable-1776605300006]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: 'script:[{value: ''area''}, {value: ''bar''}, {value: ''pie''}, {value: ''line''}, {value: ''donut''}]'
    ↓keyName [ngx.components.UIUseVariable-1776605300007]: 
    ↓model [ngx.components.UIUseVariable-1776605300008]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: 'script:this.item.config.type != null && this.item.config.type != undefined && this.item.config.type != '''' ? this.item.config.type : ''bar'''
    ↓style [ngx.components.UIUseVariable-1776605300009]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:{}
    ↓AttrRowPadding [ngx.components.UIAttribute-1776605300010]: 
      attrName: '[style.--c8o-setting-row-padding]'
      attrValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: plain:0
    ↓Event [ngx.components.UIControlEvent-1776605300011]: 
      attrName: (modelChanged)
      eventName: modelChanged
      ↓setType [ngx.components.UICustomAsyncAction-1776605300012]: 
        actionValue: 
          - xmlizable: 
            - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
            - com.twinsoft.convertigo.beans.common.FormatedContent: 
              →: |
                '		try {
                			page.item.config.type = event.out != null && event.out.item != null ? event.out.item : event.out;
                		} catch (e) {
                		} finally {
                			return;
                		}
                '
        ↓InvokeSharedAction [ngx.components.UIDynamicInvoke-1776605300013]: 
          beanData: '{"ionBean":"InvokeAction"}'
          stack: C8Oforms.MobileApplication.Application.updateState
  ↓UseHeight [ngx.components.UIUseShared-1776605300014]: 
    sharedcomponent: C8Oforms.MobileApplication.Application.TextInputSetting
    ↓label [ngx.components.UIUseVariable-1776605300015]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:this.translate.instant('size_chart')
    ↓model [ngx.components.UIUseVariable-1776605300016]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:this.item.config.height
    ↓placeholder [ngx.components.UIUseVariable-1776605300017]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:''
    ↓type [ngx.components.UIUseVariable-1776605300018]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: plain:number
    ↓suffix [ngx.components.UIUseVariable-1776605300019]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: plain:px
    ↓style [ngx.components.UIUseVariable-1776605300020]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:{}
    ↓AttrRowPadding [ngx.components.UIAttribute-1776605300021]: 
      attrName: '[style.--c8o-setting-row-padding]'
      attrValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: plain:0
    ↓Event [ngx.components.UIControlEvent-1776605300022]: 
      attrName: (modelChanged)
      eventName: modelChanged
      ↓setHeight [ngx.components.UICustomAsyncAction-1776605300023]: 
        actionValue: 
          - xmlizable: 
            - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
            - com.twinsoft.convertigo.beans.common.FormatedContent: 
              →: |
                		try {
                			page.item.config.height = event.out;
                		} catch (e) {
                		} finally {
                			return;
                		}
                
        ↓InvokeSharedAction [ngx.components.UIDynamicInvoke-1776605300024]: 
          beanData: '{"ionBean":"InvokeAction"}'
          stack: C8Oforms.MobileApplication.Application.updateState
↓Style [ngx.components.UIStyle-1776605300025]: 
  styleContent: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        →: |
          '.c8o-settings-stack{
          	display: flex;
          	flex-direction: column;
          	gap: 8px;
          	margin-bottom: 8px;
          	width: 100%;
          }'