scriptContent: 
  - xmlizable: 
    - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
    - com.twinsoft.convertigo.beans.common.FormatedContent: 
      →: |
        '/*Begin_c8o_CompImport*/
        /*End_c8o_CompImport*/
        /*Begin_c8o_CompDeclaration*/
        	/*End_c8o_CompDeclaration*/
        /*Begin_c8o_CompConstructor*/
        		/*End_c8o_CompConstructor*/
        /*Begin_c8o_CompInitialization*/
        		/*End_c8o_CompInitialization*/
        /*Begin_c8o_CompFinalization*/
        		/*End_c8o_CompFinalization*/
        /*Begin_c8o_CompChanges*/
        		/*End_c8o_CompChanges*/
        /*Begin_c8o_CompDoCheck*/
        		/*End_c8o_CompDoCheck*/
        /*Begin_c8o_CompAfterContentInit*/
        		/*End_c8o_CompAfterContentInit*/
        /*Begin_c8o_CompAfterContentChecked*/
        		/*End_c8o_CompAfterContentChecked*/
        /*Begin_c8o_CompAfterViewInit*/
        		/*End_c8o_CompAfterViewInit*/
        /*Begin_c8o_CompAfterViewChecked*/
        		/*End_c8o_CompAfterViewChecked*/
        /*Begin_c8o_CompFunction*/
        	public chartTypeLabel(value: string) {
        		if (value === "area") {
        			return this.translate.instant("Area");
        		}
        		if (value === "bar") {
        			return this.translate.instant("Bar");
        		}
        		if (value === "pie") {
        			return this.translate.instant("Pie");
        		}
        		if (value === "line") {
        			return this.translate.instant("Line");
        		}
        		if (value === "donut") {
        			return this.translate.instant("Donut");
        		}
        		return this.translate.instant(value);
        	}
        	/*End_c8o_CompFunction*/
        '
↓item [ngx.components.UICompVariable-1776605300001]: 
  value: 
↓DivSettings [ngx.components.UIDynamicElement-1776605300002]: 
  beanData: '{"ionBean":"DivTag"}'
  tagName: div
  ↓AttrClass [ngx.components.UIAttribute-1776605300003]: 
    attrName: class
    attrValue: 
      - xmlizable: 
        - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
        - MobileSmartSourceType: plain:c8o-settings-stack
  ↓UseType [ngx.components.UIUseShared-1776605300004]: 
    sharedcomponent: C8Oforms.MobileApplication.Application.ToggleSwitch
    ↓label [ngx.components.UIUseVariable-1776605300005]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:this.translate.instant('chart_type')
    ↓options [ngx.components.UIUseVariable-1776605300006]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: 'script:[{value: ''area''}, {value: ''bar''}, {value: ''pie''}, {value: ''line''}, {value: ''donut''}]'
    ↓keyName [ngx.components.UIUseVariable-1776605300007]: 
    ↓i18nCallback [ngx.components.UIUseVariable-1780068000001]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:this.chartTypeLabel.bind(this)
    ↓model [ngx.components.UIUseVariable-1776605300008]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: 'script:this.item.config.type != null && this.item.config.type != undefined && this.item.config.type != '''' ? this.item.config.type : ''bar'''
    ↓style [ngx.components.UIUseVariable-1776605300009]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:{}
    ↓AttrRowPadding [ngx.components.UIAttribute-1776605300010]: 
      attrName: '[style.--c8o-setting-row-padding]'
      attrValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: plain:0
    ↓Event [ngx.components.UIControlEvent-1776605300011]: 
      attrName: (modelChanged)
      eventName: modelChanged
      ↓setType [ngx.components.UICustomAsyncAction-1776605300012]: 
        actionValue: 
          - xmlizable: 
            - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
            - com.twinsoft.convertigo.beans.common.FormatedContent: 
              →: |
                '		try {
                			page.item.config.type = event.out != null && event.out.item != null ? event.out.item : event.out;
                		} catch (e) {
                		} finally {
                			return;
                		}
                '
        ↓InvokeSharedAction [ngx.components.UIDynamicInvoke-1776605300013]: 
          beanData: '{"ionBean":"InvokeAction"}'
          stack: C8Oforms.MobileApplication.Application.updateState
    ↓hasSeparators [ngx.components.UIUseVariable-1782919208551]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:false
    ↓disabled [ngx.components.UIUseVariable-1782919208553]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:false
    ↓tooltipEnabled [ngx.components.UIUseVariable-1782919208555]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:true
    ↓tooltipContent [ngx.components.UIUseVariable-1782919208557]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:'tooltip_chart_type'
    ↓tooltipAlwaysVisible [ngx.components.UIUseVariable-1782919208559]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:true
  ↓UseHeightMode [ngx.components.UIUseShared-1780577000001]: 
    sharedcomponent: C8Oforms.MobileApplication.Application.ToggleSwitch
    ↓label [ngx.components.UIUseVariable-1780577000002]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:this.translate.instant('chart_height')
    ↓options [ngx.components.UIUseVariable-1780577000003]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: 'script:[{value: ''auto''}, {value: ''personalized''}]'
    ↓keyName [ngx.components.UIUseVariable-1780577000004]: 
    ↓model [ngx.components.UIUseVariable-1780577000005]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: 'script:(('''' + this.item.config.height).trim().toLowerCase() == ''auto'') ? ''auto'' : ''personalized'''
    ↓style [ngx.components.UIUseVariable-1780577000006]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:{}
    ↓AttrRowPadding [ngx.components.UIAttribute-1780577000007]: 
      attrName: '[style.--c8o-setting-row-padding]'
      attrValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: plain:0
    ↓Event [ngx.components.UIControlEvent-1780577000008]: 
      attrName: (modelChanged)
      eventName: modelChanged
      ↓setHeightMode [ngx.components.UICustomAsyncAction-1780577000009]: 
        actionValue: 
          - xmlizable: 
            - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
            - com.twinsoft.convertigo.beans.common.FormatedContent: 
              →: |
                '		try {
                			var mode = event.out != null && event.out.item != null ? event.out.item : event.out;
                			if (mode == "auto") {
                				page.item.config.height = "auto";
                			}
                			else if (page.item.config.height == null || page.item.config.height == undefined || page.item.config.height == "" || ("" + page.item.config.height).trim().toLowerCase() == "auto") {
                				page.item.config.height = "400";
                			}
                		} catch (e) {
                		} finally {
                			return;
                		}
                '
        ↓InvokeSharedAction [ngx.components.UIDynamicInvoke-1780577000010]: 
          beanData: '{"ionBean":"InvokeAction"}'
          stack: C8Oforms.MobileApplication.Application.updateState
    ↓i18nCallback [ngx.components.UIUseVariable-1782919224310]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:null
    ↓hasSeparators [ngx.components.UIUseVariable-1782919224312]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:false
    ↓disabled [ngx.components.UIUseVariable-1782919224314]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:false
    ↓tooltipEnabled [ngx.components.UIUseVariable-1782919224316]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:true
    ↓tooltipContent [ngx.components.UIUseVariable-1782919224318]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:'tooltip_chart_height'
    ↓tooltipAlwaysVisible [ngx.components.UIUseVariable-1782919224320]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:true
  ↓UseHeight [ngx.components.UIUseShared-1776605300014]: 
    sharedcomponent: C8Oforms.MobileApplication.Application.TextInputSetting
    ↓AttrHeightMode [ngx.components.UIAttribute-1780577000011]: 
      attrName: '*ngIf'
      attrValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: plain:('' + this.item.config.height).trim().toLowerCase() != 'auto'
    ↓label [ngx.components.UIUseVariable-1776605300015]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:this.translate.instant('size_chart')
    ↓model [ngx.components.UIUseVariable-1776605300016]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:this.item.config.height
    ↓placeholder [ngx.components.UIUseVariable-1776605300017]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:''
    ↓type [ngx.components.UIUseVariable-1776605300018]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: plain:number
    ↓suffix [ngx.components.UIUseVariable-1776605300019]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: plain:px
    ↓style [ngx.components.UIUseVariable-1776605300020]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:{}
    ↓AttrRowPadding [ngx.components.UIAttribute-1776605300021]: 
      attrName: '[style.--c8o-setting-row-padding]'
      attrValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: plain:0
    ↓Event [ngx.components.UIControlEvent-1776605300022]: 
      attrName: (modelChanged)
      eventName: modelChanged
      ↓setHeight [ngx.components.UICustomAsyncAction-1776605300023]: 
        actionValue: 
          - xmlizable: 
            - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
            - com.twinsoft.convertigo.beans.common.FormatedContent: 
              →: |
                		try {
                			page.item.config.height = event.out;
                		} catch (e) {
                		} finally {
                			return;
                		}
                
        ↓InvokeSharedAction [ngx.components.UIDynamicInvoke-1776605300024]: 
          beanData: '{"ionBean":"InvokeAction"}'
          stack: C8Oforms.MobileApplication.Application.updateState
    ↓min [ngx.components.UIUseVariable-1782919274416]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:
    ↓tooltipEnabled [ngx.components.UIUseVariable-1782919274418]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:true
    ↓tooltipContent [ngx.components.UIUseVariable-1782919274420]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:'tooltip_chart_height'
    ↓tooltipAlwaysVisible [ngx.components.UIUseVariable-1782919274422]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:true
  ↓UseXAxis [ngx.components.UIUseShared-1777124900001]: 
    sharedcomponent: C8Oforms.MobileApplication.Application.ToggleSwitch
    ↓label [ngx.components.UIUseVariable-1777124900002]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:this.translate.instant('xaxis_chart')
    ↓options [ngx.components.UIUseVariable-1777124900003]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:['oui','non']
    ↓model [ngx.components.UIUseVariable-1777124900004]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: 'script:this.item.config.firstColAsXAxis == true ? ''oui'' : ''non'''
    ↓style [ngx.components.UIUseVariable-1777124900005]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:{}
    ↓AttrRowPadding [ngx.components.UIAttribute-1777124900006]: 
      attrName: '[style.--c8o-setting-row-padding]'
      attrValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: plain:0
    ↓Event [ngx.components.UIControlEvent-1777124900007]: 
      attrName: (modelChanged)
      eventName: modelChanged
      ↓setXAxis [ngx.components.UICustomAsyncAction-1777124900008]: 
        actionValue: 
          - xmlizable: 
            - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
            - com.twinsoft.convertigo.beans.common.FormatedContent: 
              →: |
                		try {
                			page.item.config.firstColAsXAxis = event.out == 'oui';
                		} catch (e) {
                		} finally {
                			return;
                		}
      ↓InvokeSharedAction [ngx.components.UIDynamicInvoke-1777124900009]: 
        beanData: '{"ionBean":"InvokeAction"}'
        stack: C8Oforms.MobileApplication.Application.updateState
    ↓keyName [ngx.components.UIUseVariable-1782919298028]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:null
    ↓i18nCallback [ngx.components.UIUseVariable-1782919298030]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:null
    ↓hasSeparators [ngx.components.UIUseVariable-1782919298032]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:false
    ↓disabled [ngx.components.UIUseVariable-1782919298034]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:false
    ↓tooltipEnabled [ngx.components.UIUseVariable-1782919298036]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:true
    ↓tooltipContent [ngx.components.UIUseVariable-1782919298038]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:'tooltip_chart_first_columns_as_axis'
    ↓tooltipAlwaysVisible [ngx.components.UIUseVariable-1782919298040]: 
      varValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: script:true
↓Style [ngx.components.UIStyle-1776605300025]: 
  styleContent: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        →: |
          '.c8o-settings-stack{
          	display: flex;
          	flex-direction: column;
          	gap: 8px;
          	margin-bottom: 8px;
          	width: 100%;
          }'