scriptContent: 
  - xmlizable: 
    - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
    - com.twinsoft.convertigo.beans.common.FormatedContent: 
      →: |
        '/*Begin_c8o_CompImport*/
        /*End_c8o_CompImport*/
        /*Begin_c8o_CompDeclaration*/
        	public guideCols = new Array(12);
        	private resizingIndex: number | null = null;
        	  private startX: number = 0;
        	  private startSize: number = 0;
        	/*End_c8o_CompDeclaration*/
        /*Begin_c8o_CompConstructor*/
        		this.local.totalSize = 240;
        		/*End_c8o_CompConstructor*/
        /*Begin_c8o_CompInitialization*/
        		/*End_c8o_CompInitialization*/
        /*Begin_c8o_CompFinalization*/
        		/*End_c8o_CompFinalization*/
        /*Begin_c8o_CompChanges*/
        		if (changes.cols?.currentValue) {
        			this.computeMinSize(changes.cols?.currentValue);
        		}
        		/*End_c8o_CompChanges*/
        /*Begin_c8o_CompDoCheck*/
        		/*End_c8o_CompDoCheck*/
        /*Begin_c8o_CompAfterContentInit*/
        		/*End_c8o_CompAfterContentInit*/
        /*Begin_c8o_CompAfterContentChecked*/
        		/*End_c8o_CompAfterContentChecked*/
        /*Begin_c8o_CompAfterViewInit*/
        		/*End_c8o_CompAfterViewInit*/
        /*Begin_c8o_CompAfterViewChecked*/
        		/*End_c8o_CompAfterViewChecked*/
        /*Begin_c8o_CompFunction*/
        
        	computeMinSize(cols) {
        	    this.local.minSizes = cols.map((col, index) => {
        	        // Vérification si l''une des colonnes suivantes a une taille supérieure à 0
        	        const hasNextWithSize = cols.slice(index + 1).some(nextCol => nextCol.size > 0);
        	
        	        if (col.size > 0 && hasNextWithSize) {
        	            return (1 / 12) * this.local.totalSize;
        	        } else {
        	            return "*";
        	        }
        	    });
        	}
        
        	/*End_c8o_CompFunction*/
        '
↓Style [ngx.components.UIStyle-1730821452625]: 
  styleContent: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        →: |
          ':host {
          //  --as-gutter-background-color: var(--ion-color-primary); /* Remplacez par la couleur souhaitée */
          //  --as-gutter-icon-horizontal: "";
          }
          
          //.columns {
          //	display: flex;
          //	align-items: center;
          //	justify-content: center;
          //    height: 100%;
          //    width: 100%;
          //}
          //
          //.col {
          //	height: 20px; /* ou définissez une hauteur ici */
          //  position: relative;
          //  display: flex;
          //  align-items: center;
          //}
          //
          //.gutter {
          //	width: 100%; /* Pour occuper toute la hauteur du parent */
          //  height: 100%;
          //  cursor: col-resize;
          //  user-select: none;
          //}
          //
          //.handle {
          //	position: relative;
          //	width: 3px;
          //	height: 100%;
          //	margin: 0 auto;
          //	background: #2496ff;
          //	transition: margin-top 200ms ease-out, height 200ms ease-out, background-color 200ms linear;
          //}
          //
          //.label {
          //	padding: 0 5px;
          //}
          //
          //.inset {
          //	background: rgb(0, 0, 0, 0.22);
          //	border: 1px solid rgb(255, 255, 255, 0.16);
          //	padding: 1px;
          //	border-radius: 4px;
          //	width:100%;
          //	animation-fill-mode: forwards;
          //	animation-duration: 0.5s;
          //}
          //
          //.clearfix {
          //	zoom: 1;
          //}
          //
          //.input-control {
          //	position: relative;
          //	height: 28px;
          //	width: 100%;
          //	-webkit-user-select: none;
          //	-moz-user-select: none;
          //	user-select: none;
          //}
          //
          //.guide {
          //	position: absolute;
          //	left: 0;
          //	right: 0;
          //	top: -5px;
          //	bottom: -5px;
          //	z-index: 1;
          //	pointer-events: none;
          //	opacity: 0;
          //	transition: opacity 50ms ease-in;
          //}
          //
          //.arrows {
          //	position: absolute;
          //	left: -9px;
          //	top: 50%;
          //	width: 21px;
          //	height: 13px;
          //	margin-top: -7px;
          //	background-position: -520px -260px;
          //	pointer-events: none;
          //	opacity: 0.4;
          //	transition: opacity 200ms ease;
          //}'
↓cols [ngx.components.UICompVariable-1730823427073]: 
  autoEmit: true
  value: null
↓SharedComponent_Event [ngx.components.UISharedComponentEvent-1730826575413]: 
  componentEvent: onInit
  ↓Import [ngx.components.UICustomAsyncAction-1730826587756]: 
    local_module_ng_imports: 
      - xmlizable: 
        - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
        - com.twinsoft.convertigo.beans.common.XMLVector: 
          - xmlizable: 
            - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
            - com.twinsoft.convertigo.beans.common.XMLVector: 
              - java.lang.String: 
                - ↑value: AngularSplitModule
    local_module_ts_imports: 
      - xmlizable: 
        - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
        - com.twinsoft.convertigo.beans.common.XMLVector: 
          - xmlizable: 
            - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
            - com.twinsoft.convertigo.beans.common.XMLVector: 
              - java.lang.String: 
                - ↑value: AngularSplitModule
              - java.lang.String: 
                - ↑value: angular-split
    package_dependencies: 
      - xmlizable: 
        - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
        - com.twinsoft.convertigo.beans.common.XMLVector: 
          - xmlizable: 
            - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
            - com.twinsoft.convertigo.beans.common.XMLVector: 
              - java.lang.String: 
                - ↑value: angular-split
              - java.lang.String: 
                - ↑value: 18.0.0
↓as_split [ngx.components.UIElement-1730827111422]: 
  tagName: as-split
  ↓config [ngx.components.UIAttribute-1730827129643]: 
    attrName: config
    attrValue: 
      - xmlizable: 
        - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
        - MobileSmartSourceType: plain:horizontal
  ↓Directive [ngx.components.UIControlDirective-1730827158511]: 
    directiveIndexName: i
    directiveItemName: col
    directiveSource: 
      - xmlizable: 
        - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
        - MobileSmartSourceType: script:this.cols
    ↓Tag [ngx.components.UIElement-1730827179374]: 
      tagName: as-split-area
      ↓_size_ [ngx.components.UIAttribute-1730827193621]: 
        attrName: '[size]'
        attrValue: 
          - xmlizable: 
            - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
            - MobileSmartSourceType: script:col.size / 12 * this.local.totalSize
      ↓Div [ngx.components.UIDynamicElement-1730827288108]: 
        beanData: '{"ionBean":"DivTag"}'
        tagName: div
        ↓Paragraph [ngx.components.UIDynamicElement-1730827226274]: 
          beanData: '{"ionBean":"Paragraph"}'
          tagName: p
          ↓Text [ngx.components.UIText-1730827226273]: 
            textValue: 
              - xmlizable: 
                - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
                - MobileSmartSourceType: script:col.size
        ↓Style [ngx.components.UIStyle-1730827300169]: 
          styleContent: 
            - xmlizable: 
              - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
              - com.twinsoft.convertigo.beans.common.FormatedContent: 
                →: |
                  'display: flex;
                  justify-content: center;
                  '
      ↓_size_1 [ngx.components.UIAttribute-1730828033526]: 
        attrName: '[minSize]'
        attrValue: 
          - xmlizable: 
            - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
            - MobileSmartSourceType: script:this.local.minSizes[i]
  ↓_size_1 [ngx.components.UIAttribute-1730827498952]: 
    attrName: unit
    attrValue: 
      - xmlizable: 
        - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
        - MobileSmartSourceType: plain:pixel
  ↓Style [ngx.components.UIStyle-1730827650851]: 
    styleContent: 
      - xmlizable: 
        - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
        - com.twinsoft.convertigo.beans.common.FormatedContent: 
          →: |
            'border: 1px solid #000000;
            border-radius: 4px;
            padding: 3px;
            '
  ↓_size_2 [ngx.components.UIAttribute-1730827689566]: 
    attrName: '[style.width]'
    attrValue: 
      - xmlizable: 
        - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
        - MobileSmartSourceType: script:(this.local.totalSize + ((this.cols.length -1) * 11))+'px'
  ↓_size_3 [ngx.components.UIAttribute-1730827917632]: 
    attrName: '[gutterStep]'
    attrValue: 
      - xmlizable: 
        - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
        - MobileSmartSourceType: script:this.local.totalSize / 12
  ↓_size_4 [ngx.components.UIAttribute-1730827977293]: 
    attrName: '[restrictMove]'
    attrValue: 
      - xmlizable: 
        - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
        - MobileSmartSourceType: script:true
  ↓Event [ngx.components.UIControlEvent-1730828389861]: 
    attrName: (dragEnd)
    eventName: (dragEnd)
    ↓CustomAsyncAction [ngx.components.UICustomAsyncAction-1730828398487]: 
      actionValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
          - com.twinsoft.convertigo.beans.common.FormatedContent: 
            →: |
              '		try {
              			let total = event.sizes.reduce((acc, curr) => {
              				curr = isNaN(curr) ? 0 : curr;
              				acc += curr;
              				return acc
              			}, 0);
              			let sizes = event.sizes;
              			sizes[0] = this.local.totalSize - total;
              			sizes = sizes.map((size) => {
              				return {size: size / this.local.totalSize * 12};
              			})
              			page.cols = sizes;
              			page.computeMinSize(page.cols);
              			page.ref.detectChanges();
              			page.pageOwner.updateState();
              			
              		} catch (e) {
              		
              		} finally {
              			return;
              		}
              '