scriptContent: 
  - xmlizable: 
    - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
    - com.twinsoft.convertigo.beans.common.FormatedContent: 
      →: |
        /*Begin_c8o_PageImport*/
        /*End_c8o_PageImport*/
        /*Begin_c8o_PageDeclaration*/
        	/*End_c8o_PageDeclaration*/
        /*Begin_c8o_PageConstructor*/
        		/*End_c8o_PageConstructor*/
        /*Begin_c8o_PageFunction*/
        	/*End_c8o_PageFunction*/
        
segment: path-to-modalconfigure
title: Title for modalConfigure
↓Header [ngx.components.UIDynamicElement-1678804476853]: 
  beanData: '{"ionBean":"Header"}'
  tagName: ion-header
  ↓ToolBar [ngx.components.UIDynamicElement-1678804476856]: 
    beanData: '{"ionBean":"ToolBar"}'
    tagName: ion-toolbar
    ↓ButtonSet1 [ngx.components.UIDynamicElement-1678804476859]: 
      beanData: '{"ionBean":"ButtonSet","SetPosition":"plain:end"}'
      tagName: ion-buttons
      ↓Button [ngx.components.UIDynamicElement-1678804476862]: 
        beanData: '{"ionBean":"Button"}'
        tagName: ion-button
        ↓Icon [ngx.components.UIDynamicElement-1678804476865]: 
          beanData: '{"ionBean":"Icon","IconName":"plain:close"}'
          tagName: ion-icon
        ↓Event [ngx.components.UIControlEvent-1678804476868]: 
          ↓CloseModal [ngx.components.UIDynamicAction-1678804476871]: 
            beanData: '{"ionBean":"CloseModalAction"}'
    ↓BarTitle [ngx.components.UIDynamicElement-1678804476874]: 
      beanData: '{"ionBean":"BarTitle"}'
      tagName: ion-title
      ↓Text [ngx.components.UIText-1678804476877]: 
        i18n: true
        textValue: 
          - xmlizable: 
            - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
            - MobileSmartSourceType: plain:configure
↓Content [ngx.components.UIDynamicElement-1678804405591]: 
  beanData: '{"ionBean":"Content","Padding":"plain:ion-no-padding"}'
  tagName: ion-content
  ↓Tag [ngx.components.UIElement-1678804405594]: 
    tagName: iframe
    ↓Attr [ngx.components.UIAttribute-1678804405597]: 
      attrName: '[src]'
      attrValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: 'script:this.router.sanitizer.bypassSecurityTrustResourceUrl(this.navParams.data.url == undefined ? ''https://www.convertigo.com/startprivatecloud'' : this.navParams.data.url)'
      isEnabled: false
    ↓Style [ngx.components.UIStyle-1678804405600]: 
      styleContent: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
          - com.twinsoft.convertigo.beans.common.FormatedContent: 
            →: |
              'height:calc(100% - 6px) !important;
              width: 100%;
              border-width: 0px;
              background-color: white !important;
              '
    ↓Attr1 [ngx.components.UIAttribute-1678804405603]: 
      attrName: id
      attrValue: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
          - MobileSmartSourceType: plain:ifr
↓Footer [ngx.components.UIDynamicElement-1678804405606]: 
  beanData: '{"ionBean":"Footer"}'
  isEnabled: false
  tagName: ion-footer
  ↓ToolBar [ngx.components.UIDynamicElement-1678804405609]: 
    beanData: '{"ionBean":"ToolBar"}'
    tagName: ion-toolbar
    ↓Div [ngx.components.UIDynamicElement-1678804405612]: 
      beanData: '{"ionBean":"DivTag"}'
      tagName: div
      ↓Div [ngx.components.UIDynamicElement-1678804405615]: 
        beanData: '{"ionBean":"DivTag"}'
        tagName: div
        ↓FormatLayout [ngx.components.UIDynamicAttr-1678804405618]: 
          beanData: |
            '{
             "ionBean": "FormatLayout",
             "TextAlignment": "plain:ion-text-center",
             "FlexContainerAlignment": "plain:ion-justify-content-center"
            }'
          selfClose: false
        ↓Button [ngx.components.UIDynamicElement-1678804405621]: 
          beanData: '{"ionBean":"Button","IonFill":"plain:solid"}'
          tagName: ion-button
          ↓Text [ngx.components.UIText-1678804405624]: 
            i18n: true
            textValue: 
              - xmlizable: 
                - ↑classname: com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType
                - MobileSmartSourceType: 'script:(this.navParams.data.url == undefined ? ''Continue_Trial'' : ''close'') | translate'
          ↓Event [ngx.components.UIControlEvent-1678804405627]: 
            ↓CloseModal [ngx.components.UIDynamicAction-1678804405630]: 
              beanData: '{"ionBean":"CloseModalAction"}'
          ↓Style [ngx.components.UIStyle-1678804405633]: 
            styleContent: 
              - xmlizable: 
                - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
                - com.twinsoft.convertigo.beans.common.FormatedContent: 
                  →: |
                    '/**
                     * Custom properties (sometimes referred to as CSS variables or cascading variables)
                     * are entities defined by CSS authors that contain specific values to be reused throughout a document.
                     * They are set using custom property notation, e.g.: --main-color: black;
                     * and are accessed using the var() function, e.g.: color: var(--main-color);
                     * You can find below your component''s properties you can customize within the page.
                     * If you''d like to make some customizations for whole app, please see your app Style & Theme components.
                     * For more informations see https://ionicframework.com/docs/theming.
                    **/
                    //--background	//Background of the button
                    //--background-activated	//Background of the button when pressed. Note: setting this will interfere with the Material Design ripple
                    //--background-activated-opacity	//Opacity of the button when pressed
                    //--background-focused	//Background of the button when focused with the tab key
                    //--background-focused-opacity	//Opacity of the button when focused with the tab key
                    //--background-hover	//Background of the button on hover
                    //--background-hover-opacity	//Opacity of the background on hover
                    //--border-color	//Border color of the button
                    //--border-radius	//Border radius of the button
                    //--border-style	//Border style of the button
                    //--border-width	//Border width of the button
                    //--box-shadow	//Box shadow of the button
                    //--color	//Text color of the button
                    //--color-activated	//Text color of the button when pressed
                    //--color-focused	//Text color of the button when focused with the tab key
                    //--color-hover	//Text color of the button when hover
                    //--opacity	//Opacity of the button
                    //--padding-bottom	//Bottom padding of the button
                    //--padding-end	//Right padding if direction is left-to-right, and left padding if direction is right-to-left of the button
                    //--padding-start	//Left padding if direction is left-to-right, and right padding if direction is right-to-left of the button
                    //--padding-top	//Top padding of the button
                    //--ripple-color	//Color of the button ripple effect
                    //--transition	//Transition of the button
                    	text-transform: unset;
                    	&:hover{
                    		cursor:pointer;
                    	}
                    	font-family: ''Work Sans'', sans-serif !important;
                    	span{
                    		font-family: ''Work Sans'', sans-serif !important;
                    	}
                    '
      ↓Style [ngx.components.UIStyle-1678804405636]: 
        styleContent: 
          - xmlizable: 
            - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
            - com.twinsoft.convertigo.beans.common.FormatedContent: 
              →: |
                'display: flex;
                  align-items: center;
                  justify-content: center;
                '
↓PageEvent [ngx.components.UIPageEvent-1678804405639]: 
  ↓setUrlIntoIframe [ngx.components.UICustomAction-1678804405642]: 
    actionValue: 
      - xmlizable: 
        - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
        - com.twinsoft.convertigo.beans.common.FormatedContent: 
          →: |
            '		/*let ifr = document.createElement("iframe");
            		ifr.style.height = ''calc(100% - 6px) !important'';
            		ifr.style.width = ''100%'';
            		ifr.style.borderWidth = ''0px'';
            		ifr.style.backgroundColor = ''white !important'';
            		//let url = this.router.sanitizer.bypassSecurityTrustResourceUrl(page.navParams.data.url == undefined ? ''https://www.convertigo.com/startprivatecloud'' : page.navParams.data.url)
            		ifr.src = page.navParams.data.url == undefined ? ''https://www.convertigo.com/startprivatecloud'' : page.navParams.data.url;
            		page.myContent.el.appendChild(ifr);*/
            		(document.getElementById("ifr") as any).src = page.navParams.data.url == undefined ? ''https://www.convertigo.com/startprivatecloud'' : page.navParams.data.url;
            		resolve();
            '