comment: Settings
icon: settings
scriptContent: 
  - xmlizable: 
    - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
    - com.twinsoft.convertigo.beans.common.FormatedContent: 
      →: |
        /*Begin_c8o_PageImport*/
        import { TranslateService } from '@ngx-translate/core';
        /*End_c8o_PageImport*/
        /*Begin_c8o_PageDeclaration*/
        	public fr = false;
        	public en = true;
        	public es = false;
        	public selectedItem;
        	/*End_c8o_PageDeclaration*/
        /*Begin_c8o_PageConstructor*/
        		/*End_c8o_PageConstructor*/
        /*Begin_c8o_PageFunction*/
        	/*End_c8o_PageFunction*/
        
segment: path-to-settings
title: Settings
↓Header [mobile.components.UIDynamicElement-1539697882623]: 
  beanData: '{"ionBean":"Header"}'
  tagName: ion-header
  ↓NavBar [mobile.components.UIDynamicElement-1539697882766]: 
    beanData: '{"ionBean":"NavBar","IonColor":"plain:light"}'
    tagName: ion-navbar
    ↓BarTitle [mobile.components.UIDynamicElement-1539697882909]: 
      beanData: '{"ionBean":"BarTitle"}'
      tagName: ion-title
      ↓TextFormat [mobile.components.UIDynamicElement-1539697883102]: 
        beanData: '{"ionBean":"TextFormat","TextCenter":"plain:text-center"}'
        tagName: div
        ↓Text [mobile.components.UIText-1539697883271]: 
          textValue: 
            - xmlizable: 
              - ↑classname: com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType
              - MobileSmartSourceType: plain:Convertigo Forms Builder
    ↓Button [mobile.components.UIDynamicElement-1539697883427]: 
      beanData: |
        '{
         "ionBean": "Button",
         "ButtonFormType": "plain:false",
         "MenuMode": "plain:menuToggle"
        }'
      comment: A button to toggle the menu
      tagName: button
      ↓Icon [mobile.components.UIDynamicElement-1539697883585]: 
        beanData: '{"ionBean":"Icon","IconName":"plain:menu"}'
        tagName: ion-icon
↓Content [mobile.components.UIDynamicElement-1539697883741]: 
  beanData: '{"ionBean":"Content"}'
  tagName: ion-content
  ↓DivCenter [mobile.components.UIDynamicElement-1542913501315]: 
    beanData: '{"ionBean":"DivTag"}'
    tagName: div
    ↓Style [mobile.components.UIStyle-1542913535933]: 
      styleContent: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
          - com.twinsoft.convertigo.beans.common.FormatedContent: 
            →: |
              'width: auto;
              max-width: 800px;
              min-width: 400px;
              position: absolute;
                left: 0;
                right: 0;
                margin: auto;
              '
    ↓CardContainer [mobile.components.UIDynamicElement-1539701860731]: 
      beanData: '{"ionBean":"Card"}'
      tagName: ion-card
      ↓CardContent [mobile.components.UIDynamicElement-1539701865975]: 
        beanData: '{"ionBean":"CardContent"}'
        tagName: ion-card-content
        ↓ListContainer [mobile.components.UIDynamicElement-1542918249344]: 
          beanData: '{"ionBean":"List"}'
          tagName: ion-list
          ↓GenericItem [mobile.components.UIDynamicElement-1542918256381]: 
            beanData: '{"ionBean":"GenericItem"}'
            tagName: ion-item
            ↓Label [mobile.components.UIDynamicElement-1542918265022]: 
              beanData: '{"ionBean":"Label"}'
              tagName: ion-label
              ↓TextFormat [mobile.components.UIDynamicElement-1542918275736]: 
                beanData: '{"ionBean":"TextFormat","TextCapitalize":"plain:text-capitalize"}'
                tagName: div
                ↓Text [mobile.components.UIText-1542918277646]: 
                  textValue: 
                    - xmlizable: 
                      - ↑classname: com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType
                      - MobileSmartSourceType: script:'language' | translate
            ↓SelectContainer [mobile.components.UIDynamicElement-1542918296365]: 
              beanData: '{"ionBean":"Select"}'
              tagName: ion-select
              ↓SelectOptionFR [mobile.components.UIDynamicElement-1542918296368]: 
                beanData: |
                  '{
                   "ionBean": "Option",
                   "value": "plain:fr",
                   "selected": "script:fr"
                  }'
                tagName: ion-option
                ↓Text [mobile.components.UIText-1542918296371]: 
                  textValue: 
                    - xmlizable: 
                      - ↑classname: com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType
                      - MobileSmartSourceType: plain:Français
              ↓SelectOptionEN [mobile.components.UIDynamicElement-1542918296374]: 
                beanData: |
                  '{
                   "ionBean": "Option",
                   "value": "plain:en",
                   "selected": "script:en"
                  }'
                tagName: ion-option
                ↓Text [mobile.components.UIText-1542918296377]: 
                  textValue: 
                    - xmlizable: 
                      - ↑classname: com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType
                      - MobileSmartSourceType: plain:English
              ↓SelectOptionES [mobile.components.UIDynamicElement-1542918296380]: 
                beanData: |
                  '{
                   "ionBean": "Option",
                   "value": "plain:es",
                   "selected": "script:es"
                  }'
                tagName: ion-option
                ↓Text [mobile.components.UIText-1542918296383]: 
                  textValue: 
                    - xmlizable: 
                      - ↑classname: com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType
                      - MobileSmartSourceType: plain:Español
              ↓Event [mobile.components.UIControlEvent-1542918296386]: 
                attrName: (ionChange)
                eventName: ionChange
                ↓ChangeLanguage [mobile.components.UICustomAction-1542918296389]: 
                  actionValue: 
                    - xmlizable: 
                      - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
                      - com.twinsoft.convertigo.beans.common.FormatedContent: 
                        →: |
                          		let lang = event.toString();
                          		let translate = this.getInstance(TranslateService);
                          		translate.use(lang);
                          		this.fr = false;
                          		this.en = false;
                          		this.es = false;
                          		this.selectedItem = lang;
                          		this[lang] = true;
                          		resolve();
                          
                          
                  ↓SetGlobal [mobile.components.UIDynamicAction-1542918672102]: 
                    beanData: |
                      '{
                       "ionBean": "SetGlobalAction",
                       "Property": "plain:language",
                       "Value": "script:stack[''ChangeLanguage''][''in''][''props''][''out'']"
                      }'
                  ↓IfUser [mobile.components.UIDynamicAction-1542919211217]: 
                    beanData: '{"ionBean":"IfAction","condition":"script:this.global.user != undefined"}'
                    ↓Log [mobile.components.UIDynamicAction-1542919232110]: 
                      beanData: '{"ionBean":"LogAction","message":"plain:user is defined, will save the preferences"}'
                    ↓CallSequence [mobile.components.UIDynamicAction-1542919373068]: 
                      beanData: '{"ionBean":"CallSequenceAction","requestable":"plain:C8Oforms.SetLanguage"}'
                      ↓email [mobile.components.UIControlVariable-1542920250312]: 
                        varValue: 
                          - xmlizable: 
                            - ↑classname: com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType
                            - MobileSmartSourceType: script:this.global.user
                      ↓language [mobile.components.UIControlVariable-1542920279543]: 
                        varValue: 
                          - xmlizable: 
                            - ↑classname: com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType
                            - MobileSmartSourceType: script:this.global.language
                      ↓Log [mobile.components.UIDynamicAction-1542920368436]: 
                        beanData: '{"ionBean":"LogAction","message":"plain:Language has been saved to profile"}'
                  ↓IfNotUser [mobile.components.UIDynamicAction-1542919266756]: 
                    beanData: '{"ionBean":"IfAction","condition":"script:this.global.user == undefined"}'
                    ↓Log [mobile.components.UIDynamicAction-1542919266759]: 
                      beanData: '{"ionBean":"LogAction","message":"plain:user is undefined cannot save preferences"}'
              ↓Attr [mobile.components.UIAttribute-1542918296392]: 
                attrName: '[(ngModel)]'
                attrValue: 
                  - xmlizable: 
                    - ↑classname: com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType
                    - MobileSmartSourceType: script:selectedItem
  ↓Style [mobile.components.UIStyle-1542913783197]: 
    styleContent: 
      - xmlizable: 
        - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
        - com.twinsoft.convertigo.beans.common.FormatedContent: 
          →: |
            'width:100%;
            position: relative;
            '