comment: Settings
icon: settings
menu: C8Oforms.MobileApplication.Application.MenuSelector
scriptContent: 
  - xmlizable: 
    - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
    - com.twinsoft.convertigo.beans.common.FormatedContent: 
      →: |
        /*Begin_c8o_PageImport*/
        import { TranslateService } from '@ngx-translate/core';
        /*End_c8o_PageImport*/
        /*Begin_c8o_PageDeclaration*/
        	public fr = false;
        	public en = true;
        	public es = false;
        	public selectedItem;
        	/*End_c8o_PageDeclaration*/
        /*Begin_c8o_PageConstructor*/
        		/*End_c8o_PageConstructor*/
        /*Begin_c8o_PageFunction*/
        	/*End_c8o_PageFunction*/
        
segment: path-to-settings
title: Settings
↓Header [mobile.components.UIDynamicElement-1539697882623]: 
  beanData: '{"ionBean":"Header"}'
  tagName: ion-header
  ↓NavBar [mobile.components.UIDynamicElement-1539697882766]: 
    beanData: '{"ionBean":"NavBar","IonColor":"plain:light"}'
    tagName: ion-navbar
    ↓BarTitle [mobile.components.UIDynamicElement-1539697882909]: 
      beanData: '{"ionBean":"BarTitle"}'
      tagName: ion-title
      ↓TextFormat [mobile.components.UIDynamicElement-1539697883102]: 
        beanData: '{"ionBean":"TextFormat","TextCenter":"plain:text-center"}'
        tagName: div
        ↓Text [mobile.components.UIText-1539697883271]: 
          textValue: 
            - xmlizable: 
              - ↑classname: com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType
              - MobileSmartSourceType: plain:Convertigo Forms Builder
    ↓Button [mobile.components.UIDynamicElement-1539697883427]: 
      beanData: |
        '{
         "ionBean": "Button",
         "ButtonFormType": "plain:false",
         "MenuMode": "plain:menuToggle"
        }'
      comment: A button to toggle the menu
      tagName: button
      ↓Icon [mobile.components.UIDynamicElement-1539697883585]: 
        beanData: '{"ionBean":"Icon","IconName":"plain:menu"}'
        tagName: ion-icon
    ↓ButtonSet [mobile.components.UIDynamicElement-1543518923173]: 
      beanData: '{"ionBean":"ButtonSet","SetPosition":"plain:right"}'
      tagName: ion-buttons
      ↓btEdit [mobile.components.UIDynamicElement-1543518923176]: 
        beanData: |
          '{
           "ionBean": "Button",
           "ButtonFormType": "plain:false",
           "IonSize": "plain:large"
          }'
        tagName: button
        ↓Icon [mobile.components.UIDynamicElement-1543518923179]: 
          beanData: '{"ionBean":"Icon","IconName":"plain:build"}'
          tagName: ion-icon
        ↓Event [mobile.components.UIControlEvent-1543518923182]: 
          ↓RootPage [mobile.components.UIDynamicAction-1543518923185]: 
            beanData: '{"ionBean":"RootPageAction","page":"plain:C8Oforms.MobileApplication.Application.editorPage"}'
      ↓btVisu [mobile.components.UIDynamicElement-1543518923188]: 
        beanData: |
          '{
           "ionBean": "Button",
           "ButtonFormType": "plain:false",
           "IonSize": "plain:large"
          }'
        tagName: button
        ↓Icon [mobile.components.UIDynamicElement-1543518923191]: 
          beanData: '{"ionBean":"Icon","IconName":"plain:eye"}'
          tagName: ion-icon
        ↓Event [mobile.components.UIControlEvent-1543518923194]: 
          ↓RootPage [mobile.components.UIDynamicAction-1543518923197]: 
            beanData: '{"ionBean":"RootPageAction","page":"plain:C8Oforms.MobileApplication.Application.viewerPage"}'
      ↓Attr [mobile.components.UIAttribute-1543518923200]: 
        attrName: '*ngIf'
        attrValue: 
          - xmlizable: 
            - ↑classname: com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType
            - MobileSmartSourceType: plain:this.global?.formSelected?._id != undefined
↓Content [mobile.components.UIDynamicElement-1539697883741]: 
  beanData: '{"ionBean":"Content"}'
  tagName: ion-content
  ↓Grid [mobile.components.UIDynamicElement-1543346686507]: 
    beanData: '{"ionBean":"Grid"}'
    tagName: ion-grid
    ↓GridRow [mobile.components.UIDynamicElement-1543346686510]: 
      beanData: '{"ionBean":"GridRow"}'
      tagName: ion-row
      ↓GridCol [mobile.components.UIDynamicElement-1543346686513]: 
        beanData: |
          '{
           "ionBean": "GridCol",
           "ColumnsMedium": "plain:1",
           "ColumnsLarge": "plain:2",
           "ColumnsXLarge": "plain:3"
          }'
        tagName: ion-col
      ↓GridCol1 [mobile.components.UIDynamicElement-1543346686516]: 
        beanData: |
          '{
           "ionBean": "GridCol",
           "ColumnsXSmall": "plain:12",
           "ColumnsSmall": "plain:12",
           "ColumnsMedium": "plain:10",
           "ColumnsLarge": "plain:8",
           "ColumnsXLarge": "plain:6"
          }'
        tagName: ion-col
        ↓CardContainer [mobile.components.UIDynamicElement-1543346696755]: 
          beanData: '{"ionBean":"Card"}'
          tagName: ion-card
          ↓CardContent [mobile.components.UIDynamicElement-1543346696758]: 
            beanData: '{"ionBean":"CardContent"}'
            tagName: ion-card-content
            ↓ListContainer [mobile.components.UIDynamicElement-1543346696761]: 
              beanData: '{"ionBean":"List"}'
              tagName: ion-list
              ↓GenericItem [mobile.components.UIDynamicElement-1543346696764]: 
                beanData: '{"ionBean":"GenericItem"}'
                tagName: ion-item
                ↓Label [mobile.components.UIDynamicElement-1543346696767]: 
                  beanData: '{"ionBean":"Label"}'
                  tagName: ion-label
                  ↓TextFormat [mobile.components.UIDynamicElement-1543346696770]: 
                    beanData: '{"ionBean":"TextFormat","TextCapitalize":"plain:text-capitalize"}'
                    tagName: div
                    ↓Text [mobile.components.UIText-1543346696773]: 
                      textValue: 
                        - xmlizable: 
                          - ↑classname: com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType
                          - MobileSmartSourceType: script:'language' | translate
                ↓SelectContainer [mobile.components.UIDynamicElement-1543346696776]: 
                  beanData: '{"ionBean":"Select"}'
                  tagName: ion-select
                  ↓SelectOptionFR [mobile.components.UIDynamicElement-1543346696779]: 
                    beanData: |
                      '{
                       "ionBean": "Option",
                       "value": "plain:fr",
                       "selected": "script:fr"
                      }'
                    tagName: ion-option
                    ↓Text [mobile.components.UIText-1543346696782]: 
                      textValue: 
                        - xmlizable: 
                          - ↑classname: com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType
                          - MobileSmartSourceType: plain:Français
                  ↓SelectOptionEN [mobile.components.UIDynamicElement-1543346696785]: 
                    beanData: |
                      '{
                       "ionBean": "Option",
                       "value": "plain:en",
                       "selected": "script:en"
                      }'
                    tagName: ion-option
                    ↓Text [mobile.components.UIText-1543346696788]: 
                      textValue: 
                        - xmlizable: 
                          - ↑classname: com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType
                          - MobileSmartSourceType: plain:English
                  ↓SelectOptionES [mobile.components.UIDynamicElement-1543346696791]: 
                    beanData: |
                      '{
                       "ionBean": "Option",
                       "value": "plain:es",
                       "selected": "script:es"
                      }'
                    tagName: ion-option
                    ↓Text [mobile.components.UIText-1543346696794]: 
                      textValue: 
                        - xmlizable: 
                          - ↑classname: com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType
                          - MobileSmartSourceType: plain:Español
                  ↓Event [mobile.components.UIControlEvent-1543346696797]: 
                    attrName: (ionChange)
                    eventName: ionChange
                    ↓ChangeLanguage [mobile.components.UICustomAction-1543346696800]: 
                      actionValue: 
                        - xmlizable: 
                          - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
                          - com.twinsoft.convertigo.beans.common.FormatedContent: 
                            →: |
                              		let lang = event.toString();
                              
                              		let translate = this.getInstance(TranslateService);
                              
                              		translate.use(lang);
                              
                              		this.fr = false;
                              
                              		this.en = false;
                              
                              		this.es = false;
                              
                              		this.selectedItem = lang;
                              
                              		this[lang] = true;
                              
                              		resolve();
                              
                              
                              
                              
                      ↓SetGlobal [mobile.components.UIDynamicAction-1543346696803]: 
                        beanData: |
                          '{
                           "ionBean": "SetGlobalAction",
                           "Property": "plain:language",
                           "Value": "script:stack[''ChangeLanguage''][''in''][''props''][''out'']"
                          }'
                      ↓IfUser [mobile.components.UIDynamicAction-1543346696806]: 
                        beanData: '{"ionBean":"IfAction","condition":"script:this.global.user != undefined"}'
                        ↓Log [mobile.components.UIDynamicAction-1543346696809]: 
                          beanData: '{"ionBean":"LogAction","message":"plain:user is defined, will save the preferences"}'
                        ↓CallSequence [mobile.components.UIDynamicAction-1543346696812]: 
                          beanData: '{"ionBean":"CallSequenceAction","requestable":"plain:C8Oforms.SetLanguage"}'
                          ↓email [mobile.components.UIControlVariable-1543346696815]: 
                            varValue: 
                              - xmlizable: 
                                - ↑classname: com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType
                                - MobileSmartSourceType: script:this.global.user
                          ↓language [mobile.components.UIControlVariable-1543346696818]: 
                            varValue: 
                              - xmlizable: 
                                - ↑classname: com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType
                                - MobileSmartSourceType: script:this.global.language
                          ↓Log [mobile.components.UIDynamicAction-1543346696821]: 
                            beanData: '{"ionBean":"LogAction","message":"plain:Language has been saved to profile"}'
                      ↓IfNotUser [mobile.components.UIDynamicAction-1543346696824]: 
                        beanData: '{"ionBean":"IfAction","condition":"script:this.global.user == undefined"}'
                        ↓Log [mobile.components.UIDynamicAction-1543346696827]: 
                          beanData: '{"ionBean":"LogAction","message":"plain:user is undefined cannot save preferences"}'
                  ↓Attr [mobile.components.UIAttribute-1543346696830]: 
                    attrName: '[(ngModel)]'
                    attrValue: 
                      - xmlizable: 
                        - ↑classname: com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType
                        - MobileSmartSourceType: script:selectedItem
      ↓GridCol2 [mobile.components.UIDynamicElement-1543346687428]: 
        beanData: |
          '{
           "ionBean": "GridCol",
           "ColumnsMedium": "plain:1",
           "ColumnsLarge": "plain:2",
           "ColumnsXLarge": "plain:3"
          }'
        tagName: ion-col