comment: Settings
icon: settings
segment: path-to-settings
title: Settings
↓Header [mobile.components.UIDynamicElement-1539697882623]: 
  beanData: '{"ionBean":"Header"}'
  tagName: ion-header
  ↓NavBar [mobile.components.UIDynamicElement-1539697882766]: 
    beanData: '{"ionBean":"NavBar","IonColor":"plain:light"}'
    tagName: ion-navbar
    ↓BarTitle [mobile.components.UIDynamicElement-1539697882909]: 
      beanData: '{"ionBean":"BarTitle"}'
      tagName: ion-title
      ↓TextFormat [mobile.components.UIDynamicElement-1539697883102]: 
        beanData: '{"ionBean":"TextFormat","TextCenter":"plain:text-center"}'
        tagName: div
        ↓Text [mobile.components.UIText-1539697883271]: 
          textValue: 
            - xmlizable: 
              - ↑classname: com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType
              - MobileSmartSourceType: plain:Convertigo Forms Builder
    ↓Button [mobile.components.UIDynamicElement-1539697883427]: 
      beanData: |
        '{
         "ionBean": "Button",
         "ButtonFormType": "plain:false",
         "MenuMode": "plain:menuToggle"
        }'
      comment: A button to toggle the menu
      tagName: button
      ↓Icon [mobile.components.UIDynamicElement-1539697883585]: 
        beanData: '{"ionBean":"Icon","IconName":"plain:menu"}'
        tagName: ion-icon
↓Content [mobile.components.UIDynamicElement-1539697883741]: 
  beanData: '{"ionBean":"Content"}'
  tagName: ion-content
  ↓DivLeft [mobile.components.UIDynamicElement-1542913498083]: 
    beanData: '{"ionBean":"DivTag"}'
    tagName: div
    ↓Style [mobile.components.UIStyle-1542913510731]: 
      styleContent: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
          - com.twinsoft.convertigo.beans.common.FormatedContent: 
            →: |
              width:10%;
              float:left;
              
  ↓DivCenter [mobile.components.UIDynamicElement-1542913501315]: 
    beanData: '{"ionBean":"DivTag"}'
    tagName: div
    ↓Style [mobile.components.UIStyle-1542913535933]: 
      styleContent: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
          - com.twinsoft.convertigo.beans.common.FormatedContent: 
            →: |
              'width:80%;
              position: absolute;
                left: 0;
                right: 0;
                margin: auto;
              '
    ↓CardContainer [mobile.components.UIDynamicElement-1539701860731]: 
      beanData: '{"ionBean":"Card"}'
      tagName: ion-card
      ↓CardContent [mobile.components.UIDynamicElement-1539701865975]: 
        beanData: '{"ionBean":"CardContent"}'
        tagName: ion-card-content
        ↓ListContainer [mobile.components.UIDynamicElement-1539701979178]: 
          beanData: '{"ionBean":"List"}'
          tagName: ion-list
          ↓GenericItem [mobile.components.UIDynamicElement-1539702334390]: 
            beanData: '{"ionBean":"GenericItem"}'
            tagName: ion-item
            ↓Label [mobile.components.UIDynamicElement-1539702363524]: 
              beanData: '{"ionBean":"Label"}'
              tagName: ion-label
              ↓Text [mobile.components.UIText-1539702024213]: 
                textValue: 
                  - xmlizable: 
                    - ↑classname: com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType
                    - MobileSmartSourceType: plain:Language
            ↓SelectContainer [mobile.components.UIDynamicElement-1539702431303]: 
              beanData: '{"ionBean":"Select"}'
              tagName: ion-select
              ↓SelectOption [mobile.components.UIDynamicElement-1539702434803]: 
                beanData: '{"ionBean":"Option","value":"plain:Francais"}'
                tagName: ion-option
                ↓Text [mobile.components.UIText-1539702634380]: 
                  textValue: 
                    - xmlizable: 
                      - ↑classname: com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType
                      - MobileSmartSourceType: plain:Francais
              ↓SelectOption1 [mobile.components.UIDynamicElement-1539702441690]: 
                beanData: |
                  '{
                   "ionBean": "Option",
                   "value": "plain:English",
                   "selected": "script:true"
                  }'
                tagName: ion-option
                ↓Text [mobile.components.UIText-1539702640034]: 
                  textValue: 
                    - xmlizable: 
                      - ↑classname: com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType
                      - MobileSmartSourceType: plain:English
  ↓DivRight [mobile.components.UIDynamicElement-1542913503334]: 
    beanData: '{"ionBean":"DivTag"}'
    tagName: div
    ↓Style [mobile.components.UIStyle-1542913512653]: 
      styleContent: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
          - com.twinsoft.convertigo.beans.common.FormatedContent: 
            →: |
              'width:10%;
               float: right;
              '
  ↓Style [mobile.components.UIStyle-1542913783197]: 
    styleContent: 
      - xmlizable: 
        - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
        - com.twinsoft.convertigo.beans.common.FormatedContent: 
          →: |
            'width:100%;
            position: relative;
            '