# This is a basic workflow to help you get started with Actions

name: build_and_deploy

# Controls when the action will run. 
on: 
  push:
  # Triggers the workflow on push or pull request events but only for the develop branch
  #push:
   # tags:
    #  - '**-beta**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build and deploy Convertigo Forms betas versions
        env:
          TESTENDPOINT: ${{secrets.testEndpoint}}
          DEPLOYSERVER: ${{secrets.testEndpoint}}
          TESTUSERADMIN: ${{secrets.testUserAdmin}}
          TESTUSERPASSWORD: ${{secrets.testUserPassword}}
        run: sh gradlew --no-daemon --stacktrace --info car deploy -Pconvertigo.load.mobileApplicationEndpoint="$TESTENDPOINT" -Pconvertigo.deploy.server="$DEPLOYSERVER" -Pconvertigo.deploy.user="$TESTUSERADMIN" -Pconvertigo.deploy.password="$TESTUSERPASSWORD"
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
